/**
 * Google AI Models Configuration
 * Centralized configuration for all Google AI models.
 */

import { ModelProvider, ModelCapability, ModelConfig, ProviderConfig } from './models';

export const GOOGLE_PROVIDER_CONFIG: ProviderConfig = {
  id: "google",
  name: "Google AI",
  logo: "google",
  envKey: "GOOGLE_GENERATIVE_AI_API_KEY",
};

export const GOOGLE_MODELS: ModelConfig[] = [
  // Gemini Series
  {
    id: "google/gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.07, output: 0.30 },
    description: "Fast multimodal model with extended thinking",
  },
  {
    id: "google/gemini-1.5-flash-8b",
    name: "Gemini 1.5 Flash 8B",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.04, output: 0.15 },
    description: "Smallest Flash model",
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 1.00, output: 5.00 },
    description: "1M context window",
  },
  {
    id: "google/gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.10, output: 0.40 },
    description: "Next-gen multimodal model",
  },
  {
    id: "google/gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.07, output: 0.30 },
    description: "Efficient 2.0 model",
  },
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.30, output: 3.00 },
    description: "Fast multimodal with extended thinking",
    isDefault: true,
  },
  {
    id: "google/gemini-2.5-flash-image",
    name: "Gemini 2.5 Flash Image",
    provider: "google",
    contextWindow: 33792,
    capabilities: ["vision"],
    pricing: { input: 0.30, output: 30.00 },
    description: "Image generation",
  },
  {
    id: "google/gemini-2.5-flash-image-preview",
    name: "Gemini 2.5 Flash Image Preview",
    provider: "google",
    contextWindow: 33792,
    capabilities: ["vision"],
    pricing: { input: 0.30, output: 30.00 },
    description: "Image generation preview",
  },
  {
    id: "google/gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.10, output: 0.40 },
    description: "Lightweight fast model",
  },
  {
    id: "google/gemini-2.5-flash-lite-preview-06-17",
    name: "Gemini 2.5 Flash Lite Preview (Jun 2017)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.10, output: 0.40 },
    description: "June 2017 preview model",
  },
  {
    id: "google/gemini-2.5-flash-lite-preview-09-2025",
    name: "Gemini 2.5 Flash Lite Preview (Sep 2025)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.10, output: 0.40 },
    description: "September 2025 preview model",
  },
  {
    id: "google/gemini-2.5-flash-preview-04-17",
    name: "Gemini 2.5 Flash Preview (Apr 2017)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.15, output: 0.60 },
    description: "April 2017 preview model",
  },
  {
    id: "google/gemini-2.5-flash-preview-05-20",
    name: "Gemini 2.5 Flash Preview (May 2020)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.15, output: 0.60 },
    description: "May 2020 preview model",
  },
  {
    id: "google/gemini-2.5-flash-preview-09-2025",
    name: "Gemini 2.5 Flash Preview (Sep 2025)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.30, output: 3.00 },
    description: "September 2025 preview model",
  },
  {
    id: "google/gemini-2.5-flash-preview-tts",
    name: "Gemini 2.5 Flash TTS",
    provider: "google",
    contextWindow: 8192,
    capabilities: ["audio"],
    pricing: { input: 0.50, output: 10.00 },
    description: "Text-to-speech model",
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 1.00, output: 10.00 },
    description: "Most capable Gemini for complex tasks",
  },
  {
    id: "google/gemini-2.5-pro-preview-05-06",
    name: "Gemini 2.5 Pro Preview (May 2006)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 1.00, output: 10.00 },
    description: "May 2006 preview model",
  },
  {
    id: "google/gemini-2.5-pro-preview-06-05",
    name: "Gemini 2.5 Pro Preview (Jun 2005)",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 1.00, output: 10.00 },
    description: "June 2005 preview model",
  },
  {
    id: "google/gemini-2.5-pro-preview-tts",
    name: "Gemini 2.5 Pro TTS",
    provider: "google",
    contextWindow: 8192,
    capabilities: ["audio"],
    pricing: { input: 1.00, output: 20.00 },
    description: "High-quality text-to-speech",
  },
  {
    id: "google/gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 2.00, output: 12.00 },
    description: "Next-gen preview model",
  },
  {
    id: "google/gemini-embedding-001",
    name: "Gemini Embedding",
    provider: "google",
    contextWindow: 2048,
    capabilities: ["embedding"],
    pricing: { input: 0.15, output: 0 },
    description: "Text embeddings",
  },
  {
    id: "google/gemini-flash-latest",
    name: "Gemini Flash Latest",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "reasoning", "vision", "code"],
    pricing: { input: 0.30, output: 3.00 },
    description: "Latest fast multimodal model",
  },
  {
    id: "google/gemini-flash-lite-latest",
    name: "Gemini Flash Lite Latest",
    provider: "google",
    contextWindow: 1048576,
    capabilities: ["chat", "vision", "code"],
    pricing: { input: 0.10, output: 0.40 },
    description: "Latest lightweight model",
  },
  {
    id: "google/gemini-live-2.5-flash",
    name: "Gemini Live 2.5 Flash",
    provider: "google",
    contextWindow: 131072,
    capabilities: ["chat", "vision", "audio"],
    pricing: { input: 0.50, output: 2.00 },
    description: "Real-time multimodal processing",
  },
  {
    id: "google/gemini-live-2.5-flash-preview-native-audio",
    name: "Gemini Live 2.5 Flash Native Audio",
    provider: "google",
    contextWindow: 131072,
    capabilities: ["chat", "vision", "audio"],
    pricing: { input: 0.50, output: 2.00 },
    description: "Real-time with native audio support",
  },
];